// ====== DATA WIKI — edit di sini, halaman ikut berubah ======
// Gambar: taruh screenshot di images/<nama>.png
const STONES = [
 {id:"enchant-stone",name:"Enchant Stone",
  desc:"Apply a raondom buff to your Fishing Rod!",
  obtain:["You can get those Enchant Stones ( 1 in 2.9k ) at Fisherman Island, Ocean, Kohana, Coral Reefs, Esoteric Depths, Tropical Grove, Planetary Observatory and Kohana Lab."],
  where:"Esoteric Depths Altar."},
 {id:"super-enchant-stone",name:"Super Enchant Stone",
  desc:"Supercharge your Fishing Rod!",
  obtain:["You can obtain it by completing a quest from the Esoteric Gatekeeper NPC in the Esoteric Depths.",
    "Quest : Enchant a rod 5 times" ],
  where:"Esoteric Depths Altar."},
 {id:"transcended-stone",name:"Transcended Stone",
  desc:"Allows you to apply a second rod enchant.",
  obtain:["Sacrifice a SECRET fish for 1 Transcended Stone at the Temple Guardian NPC in the Sacred Temple."],
  where:"Sacred Temple Altar."},
 {id:"evolved-enchant-stone",name:"Evolved Enchant Stone",
  desc:"Apply a evolved buff to your Fishing Rod!",
  obtain:["You can get those Evolved Enchant Stone ( 1 in 30k ) at Ancient Ruin."],
  where:"Esoteric Depths Altar."},
 {id:"runic-enchant-stone",name:"Runic Enchant Stone",
  desc:"Apply a runic buff to your Fishing Rod!",
  obtain:["You can get those Runic Enchant Stone ( 1 in 700k ) at Underwater city and Sewers."],
  where:"Esoteric Depths Altar."},
 {id:"withering-stone",name:"Withering Stone",
  desc:"Apply the Withering Stone buff which can only be used on your second Withering Rod to enchant it!",
  obtain:["You can obtain it by completing a quest from the Lucid NPC in the Copper canyon.",
    "Quest : Own a Withering Rod", "Catch a Runic Enchant Stone", "Catch 4M rarity worh of fish",
    "Catch 50 fish while using PERFECT! throw" ],
  where:"Sacred Temple Altar."}
];
const ENCHANTS = [
  // Enchant Stone
 {name:"Stargazer I",effect:"+60% Luck at night",stone:"enchant-stone",chance:"7.5%"},
 {name:"Glistening I",effect:"+10% Shiny fish chance",stone:"enchant-stone",chance:"7.5%"},
 {name:"Stormhunter I",effect:"+80% Luck during rain",stone:"enchant-stone",chance:"7.5%"},
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"enchant-stone",chance:"5%"},
 {name:"XPerienced I",effect:"x1.5 XP from all fish catches",stone:"enchant-stone",chance:"7.5%"},
 {name:"Mutation Hunter I",effect:"+10% Chance for mutation",stone:"enchant-stone",chance:"10%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"enchant-stone",chance:"5%"},
 {name:"Big Hunter I",effect:"Makes fish 10% bigger",stone:"enchant-stone",chance:"7.5%"},
 {name:"Reeler I",effect:"Reel in fish 7% faster",stone:"enchant-stone",chance:"7.5%"},
 {name:"Gold Digger I",effect:"Constant 10% chance for Gold mutation",stone:"enchant-stone",chance:"7.5%"},
 {name:"Leprechaun I",effect:"+30% Luck",stone:"enchant-stone",chance:"10%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"enchant-stone",chance:"7.5%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"enchant-stone",chance:"5%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"enchant-stone",chance:"5%"},
 // Super Enchant Stone
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"super-enchant-stone",chance:"20%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"super-enchant-stone",chance:"20%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"super-enchant-stone",chance:"20%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"super-enchant-stone",chance:"20%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"super-enchant-stone",chance:"20%"},
 // Transcended Stone
 {name:"Perfection",effect:"Gurenteed 'Perfect' throws while auto fishing",stone:"transcended-stone",chance:"4%"},
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"transcended-stone",chance:"5%"},
 {name:"Stargazer I",effect:"+60% Luck at night",stone:"transcended-stone",chance:"7.5%"},
 {name:"Glistening I",effect:"+10% Shiny fish chance",stone:"transcended-stone",chance:"7.5%"},
 {name:"Stormhunter I",effect:"+80% Luck during rain",stone:"transcended-stone",chance:"7.5%"},
 {name:"XPerienced I",effect:"x1.5 XP from all fish catches",stone:"transcended-stone",chance:"7.5%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"transcended-stone",chance:"5%"},
 {name:"Big Hunter I",effect:"Makes fish 10% bigger",stone:"transcended-stone",chance:"7.5%"},
 {name:"Reeler I",effect:"Reel in fish 7% faster",stone:"transcended-stone",chance:"7.5%"},
 {name:"Gold Digger I",effect:"Constant 10% chance for Gold mutation",stone:"transcended-stone",chance:"7.5%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"transcended-stone",chance:"7.5%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"transcended-stone",chance:"5%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"transcended-stone",chance:"5%"},
 // Evolved Enchant Stone
 {name:"SECRET Hunter",effect:"+400% SECRET Chance",stone:"evolved-enchant-stone"},
 {name:"Gemstone Hunter I",effect:"+35% Gemstone mutation chance",stone:"evolved-enchant-stone"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"evolved-enchant-stone"},
 {name:"Stargazer II",effect:"+100% Luck at night",stone:"evolved-enchant-stone"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"evolved-enchant-stone"},
 {name:"Shark Hunter I",effect:"Increase all Shark chances by 175%",stone:"evolved-enchant-stone"},
 {name:"Stormhunter II",effect:"+140% Luck during rain",stone:"evolved-enchant-stone"},
 {name:"Fairy Hunter I",effect:"+35 Fairy Dust mutation chance",stone:"evolved-enchant-stone"},
 {name:"Reeler II",effect:"Reel in fish 15% faster",stone:"evolved-enchant-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"evolved-enchant-stone"},
 // Runic Enchant Stone
 {name:"FORGOTTEN Hunter",effect:"+500% FORGOTTEN Chance",stone:"runic-enchant-stone"},
 {name:"Glistening II",effect:"+20% Shiny fish chance",stone:"runic-enchant-stone"},
 {name:"XPerienced II",effect:"x2 XP from all fish catches",stone:"runic-enchant-stone"},
 {name:"Shark Hunter II",effect:"Increase all Shark chances by 275%",stone:"runic-enchant-stone"},
 {name:"Cursed II",effect:"-100% Luck, +100% mutation chance",stone:"runic-enchant-stone"},
 {name:"Empowered II",effect:"+35% luck, +15% faster reel",stone:"runic-enchant-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"runic-enchant-stone"},
 // Withering Stone
 {name:"SECRET Hunter",effect:"+400% SECRET Chance",stone:"withering-stone"},
 {name:"Shark Hunter II",effect:"Increase all Shark chances by 275%",stone:"withering-stone"},
 {name:"Fairy Hunter II",effect:"+60 Fairy Dust mutation chance",stone:"withering-stone"},
 {name:"Big Hunter II",effect:"Makes fish 15% bigger",stone:"withering-stone"},
 {name:"Cursed II",effect:"-100% Luck, +100% mutation chance",stone:"withering-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"withering-stone"},
 {name:"Empowered III",effect:"+65% luck, +15% faster reel",stone:"withering-stone"}
];
const ISLANDS = [
 {id:"fisherman-island",name:"Fisherman Island"},
 {id:"ocean",name:"Ocean"},

 {id:"unknown",name:"???"}
];
const FISH = [
  // Fisherman
 {name:"Azure Damsel",rarity:"Common",chance:"1 in 2",island:"fisherman-island"},
 {name:"Clownfish",rarity:"Common",chance:"1 in 2",island:"fisherman-island"},
 {name:"Watanabei Angelfish",rarity:"Common",chance:"1 in 4",island:"fisherman-island"},
 {name:"White Tang",rarity:"Common",chance:"1 in 5",island:"fisherman-island"},
 {name:"Pygmy Goby",rarity:"Common",chance:"1 in 6",island:"fisherman-island"},
 {name:"Herring Fish",rarity:"Common",chance:"1 in 10",island:"fisherman-island"},
 {name:"Strawberry Dotty",rarity:"Common",chance:"1 in 20",island:"fisherman-island"},
 {name:"Copperband Butterfly",rarity:"Common",chance:"1 in 20",island:"fisherman-island"},
 {name:"Old Boot",rarity:"Common",chance:"1 in 25",island:"fisherman-island"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Yellow Damselfish",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Gear Fish",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Bandit Angelfish",rarity:"Uncommon",chance:"1 in 65",island:"fisherman-island"},
 {name:"Flame Angelfish",rarity:"Uncommon",chance:"1 in 100",island:"fisherman-island"},
 {name:"Glacierfinsnapper",rarity:"Uncommon",chance:"1 in 100",island:"fisherman-island"},
 {name:"Korean Angelfish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Ballina Angelfish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Barracuda Fish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Frog",rarity:"Rare",chance:"1 in 350",island:"fisherman-island"},
 {name:"Darwin Clownfish",rarity:"Rare",chance:"1 in 750",island:"fisherman-island"},
 {name:"Dorhey Tang",rarity:"Epic",chance:"1 in 1k",island:"fisherman-island"},
 {name:"Dogfish",rarity:"Epic",chance:"1 in 2k",island:"fisherman-island"},
 {name:"Enchant Stone",rarity:"Epic",chance:"1 in 2.90k",island:"fisherman-island"},
 {name:"King Frog",rarity:"Epic",chance:"1 in 3k",island:"fisherman-island"},
 {name:"Unicorn Tang",rarity:"Epic",chance:"1 in 4.50k",island:"fisherman-island"},
 {name:"Lined Cardinal Fish",rarity:"Legendary",chance:"1 in 5.50k",island:"fisherman-island"},
 {name:"Yellowfin Tuna",rarity:"Legendary",chance:"1 in 7.50k",island:"fisherman-island"},
 {name:"Lake Sturgeon",rarity:"Legendary",chance:"1 in 20k",island:"fisherman-island"},
 {name:"Dotted Stingray",rarity:"Mythic",chance:"1 in 91k",island:"fisherman-island"},
 {name:"Crystal Crab",rarity:"SECRET",chance:"1 in 750k",island:"fisherman-island",weight:"110.52K kg - 130.96K kg",big:"140.96K kg - 155.31K kg"},
 {name:"Orca",rarity:"SECRET",chance:"1 in 1.50M",island:"fisherman-island",weight:"115.47K kg - 126.78K kg",big:"140.31K kg - 175.81M kg"},
 // Ocean
 {name:"Yellowstate Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Vintage Blue Tang",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Masked Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Conspi Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Skunk Tilefish",rarity:"Common",chance:"1 in 7",island:"ocean"},
 {name:"Fade Tang",rarity:"Common",chance:"1 in 15",island:"ocean"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Cypress Ratua",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Curious Garfish",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Purp Blisfish",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Blue-Banded Goby",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Tricolore Butterfly",rarity:"Uncommon",chance:"1 in 70",island:"ocean"},
 {name:"Vintage Damsel",rarity:"Uncommon",chance:"1 in 135",island:"ocean"},
 {name:"Jawel Tang",rarity:"Rare",chance:"1 in 250",island:"ocean"},
 {name:"Traffic Cone Fish",rarity:"Rare",chance:"1 in 300",island:"ocean"},
 {name:"Cute Octopus",rarity:"Rare",chance:"1 in 300",island:"ocean"},
 {name:"Candy Butterfly",rarity:"Rare",chance:"1 in 375",island:"ocean"},
 {name:"Cow Clownfish",rarity:"Epic",chance:"1 in 1k",island:"ocean"},
 {name:"Expensive Chain",rarity:"Epic",chance:"1 in 1.50k",island:"ocean"},
 {name:"Blue Moonfish",rarity:"Epic",chance:"1 in 2k",island:"ocean"},
 {name:"Narwhal",rarity:"Epic",chance:"1 in 2k",island:"ocean"},
 {name:"Enchant Stone",rarity:"Epic",chance:"1 in 2.90k",island:"ocean"},
 {name:"Moorish Idol",rarity:"Epic",chance:"1 in 3.33k",island:"ocean"},
 {name:"Diamond Ring",rarity:"Legendary",chance:"1 in 5k",island:"ocean"},
 {name:"Slurpfish Chromis",rarity:"Legendary",chance:"1 in 8k",island:"ocean"},
 {name:"Chrome Tuna",rarity:"Legendary",chance:"1 in 9k",island:"ocean"},
 {name:"Ruby",rarity:"Legendary",chance:"1 in 15k",island:"ocean"},
 {name:"Mantan Ray",rarity:"Mythic",chance:"1 in 50k",island:"ocean"},
 {name:"Hammerhead Shark",rarity:"Mythic",chance:"1 in 100k",island:"ocean"},
 {name:"Sharp One",rarity:"Mythic",chance:"1 in 105k",island:"ocean"},
 {name:"Blob Shark",rarity:"SECRET",chance:"1 in 250k",island:"ocean",weight:"532.2kg - 590.5kg",big:"638.5kg - 753.3kg"},
 {name:"Ghost Shark",rarity:"SECRET",chance:"1 in 500k",island:"ocean",weight:"1.09k kg - 1.21k kg",big:"1.52k kg - 1.69k kg"},
 {name:"Skeleton Narwhal",rarity:"SECRET",chance:"1 in 600k",island:"ocean",weight:"339kg - 509kg",big:"620kg - 700kg"},
 {name:"Worm Fish",rarity:"SECRET",chance:"1 in 3M",island:"ocean",weight:"106.95k kg - 112.04k kg",big:"130.63k kg - 145.85k kg"},
 {name:"Megalodon",rarity:"SECRET",chance:"1 in 4M",island:"ocean",weather:"Megalodon Hunt",weight:"305k kg - 365k kg",big:"395k kg - 450k kg"},
 {name:"Bloodmoon Whale",rarity:"SECRET",chance:"1 in 5M",island:"ocean",weather:"Admin Bloodmoon",weight:"362.78k kg - 464.18k kg",big:"472.11k kg - 525.58k kg"},
 {name:"Frostmoon Whale",rarity:"SECRET",chance:"1 in 5M",island:"ocean",weather:"Admin Frostmoon",weight:"362.78k kg - 464.18k kg",big:"472.11k kg - 525.58k kg"},
 {name:"Glacial Serpent",rarity:"SECRET",chance:"1 in 6M",island:"ocean",weather:"Glacial Serpent Hunt",weight:"890k kg - 940k kg",big:"960k kg - 990k kg"},
 {name:"Thunderzilla",rarity:"FORGOTTEN",chance:"1 in 30M",island:"ocean",weather:"Thunderzilla Hunt",weight:"920K kg - 970K kg",big:"990K kg - 1.10M kg"},

 // ???
 {name:"Sunken Hadalith",rarity:"SECRET",chance:"???",island:"unknown",time:"???",weather:"???",weight:"???",big:"???"},
 {name:"Robot Kraken",rarity:"SECRET",chance:"1 in 3.50M",island:"unknown",weight:"259.82k kg - 389.73k kg",big:"419.60k kg - 586.47k kg"},
];
const SOON = [
 {id:"rods",name:"Rods",desc:"Semua pancingan, statistik, dan cara mendapatkannya."},
 {id:"baits",name:"Baits",desc:"Umpan dan efek Luck-nya."}
];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const PH="data:image/svg+xml,"+encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120'><rect width='120' height='120' rx='14' fill='#c9dadf'/><text x='60' y='66' font-size='13' text-anchor='middle' fill='#5b7580' font-family='sans-serif'>Proses...</text></svg>");
const img=(src,alt,cls)=>`<img class="${cls||""}" src="${src}" alt="${alt}" loading="lazy" onerror="this.onerror=null;this.src=PH">`;
