const ISLANDS = [
 {id:"fisherman-island",name:"Fisherman Island"},
 {id:"planetary-observatory",name:"Planetary Observatory"},
 {id:"ocean",name:"Ocean"},
 {id:"kohana",name:"Kohana"},
 {id:"kohana-lab",name:"Kohana Lab"}, 
 {id:"kohana-volcano",name:"Kohana Volcano"},
 {id:"volcanic-cavern",name:"Volcanic Cavern"},
 {id:"lava-basin",name:"Lava Basin"},
 {id:"creater-island",name:"Creater Island"},
 {id:"coral-reefs",name:"Coral Reefs"},
 {id:"esoteric-depths",name:"Esoteric Depths"},
 {id:"tropical-grove",name:"Tropical Grove"},
 {id:"sisyphus-statue",name:"Sisyphus Statue"},
 {id:"treasure-room",name:"Treasure Room"},
 {id:"ancient-jungle",name:"Ancient Jugle"},
 {id:"underground-cellar",name:"Underground Cellar"},
 {id:"sacred-temple",name:"Sacred Temple"},
 {id:"ancient-ruin",name:"Ancient Ruin"},

 {id:"unknown",name:"???"}
];
const FISH = [
  // Fisherman
 {name:"Azure Damsel",rarity:"Common",chance:"1 in 2",island:"fisherman-island"},
 {name:"Clownfish",rarity:"Common",chance:"1 in 2",island:"fisherman-island"},
 {name:"Watanabei Angelfish",rarity:"Common",chance:"1 in 4",island:"fisherman-island"},
 {name:"White Tang",rarity:"Common",chance:"1 in 5",island:"fisherman-island"},
 {name:"Pygmy Goby",rarity:"Common",chance:"1 in 6",island:"fisherman-island"},
 {name:"Herring Fish",rarity:"Common",chance:"1 in 10",island:"fisherman-island"},
 {name:"Strawberry Dotty",rarity:"Common",chance:"1 in 20",island:"fisherman-island"},
 {name:"Copperband Butterfly",rarity:"Common",chance:"1 in 20",island:"fisherman-island"},
 {name:"Old Boot",rarity:"Common",chance:"1 in 25",island:"fisherman-island"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Yellow Damselfish",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Gear Fish",rarity:"Uncommon",chance:"1 in 50",island:"fisherman-island"},
 {name:"Bandit Angelfish",rarity:"Uncommon",chance:"1 in 65",island:"fisherman-island"},
 {name:"Flame Angelfish",rarity:"Uncommon",chance:"1 in 100",island:"fisherman-island"},
 {name:"Glacierfin Snapper",rarity:"Uncommon",chance:"1 in 100",island:"fisherman-island"},
 {name:"Korean Angelfish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Ballina Angelfish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Barracuda Fish",rarity:"Rare",chance:"1 in 300",island:"fisherman-island"},
 {name:"Frog",rarity:"Rare",chance:"1 in 350",island:"fisherman-island"},
 {name:"Darwin Clownfish",rarity:"Rare",chance:"1 in 750",island:"fisherman-island"},
 {name:"Dorhey Tang",rarity:"Epic",chance:"1 in 1k",island:"fisherman-island"},
 {name:"Dogfish",rarity:"Epic",chance:"1 in 2k",island:"fisherman-island"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"fisherman-island"},
 {name:"King Frog",rarity:"Epic",chance:"1 in 3k",island:"fisherman-island"},
 {name:"Unicorn Tang",rarity:"Epic",chance:"1 in 4.50k",island:"fisherman-island"},
 {name:"Lined Cardinal Fish",rarity:"Legendary",chance:"1 in 5.50k",island:"fisherman-island"},
 {name:"Yellowfin Tuna",rarity:"Legendary",chance:"1 in 7.50k",island:"fisherman-island"},
 {name:"Lake Sturgeon",rarity:"Legendary",chance:"1 in 20k",island:"fisherman-island"},
 {name:"Dotted Stingray",rarity:"Mythic",chance:"1 in 91k",island:"fisherman-island"},
 {name:"Crystal Crab",rarity:"SECRET",chance:"1 in 750k",island:"fisherman-island",weight:"110.52K kg - 130.96K kg",big:"140.96K kg - 155.31K kg"},
 {name:"Orca",rarity:"SECRET",chance:"1 in 1.50M",island:"fisherman-island",weight:"115.47K kg - 126.78K kg",big:"140.31K kg - 175.81M kg"},
 // Planetary Observatory
 {name:"Yellowstate Angelfish",rarity:"Common",chance:"1 in 2",island:"planetary-observatory"},
 {name:"Vintage Blue Tang",rarity:"Common",chance:"1 in 2",island:"planetary-observatory"},
 {name:"Masked Angelfish",rarity:"Common",chance:"1 in 2",island:"planetary-observatory"},
 {name:"Conspi Angelfish",rarity:"Common",chance:"1 in 2",island:"planetary-observatory"},
 {name:"Skunk Tilefish",rarity:"Common",chance:"1 in 7",island:"planetary-observatory"},
 {name:"Fade Tang",rarity:"Common",chance:"1 in 15",island:"planetary-observatory"},
 {name:"Cosmic Seastar",rarity:"Common Ext",chance:"1 in 40",island:"planetary-observatory"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Cypress Ratua",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Curious Garfish",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Purp Blisfish",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Blue-Banded Goby",rarity:"Uncommon",chance:"1 in 50",island:"planetary-observatory"},
 {name:"Tricolore Butterfly",rarity:"Uncommon",chance:"1 in 70",island:"planetary-observatory"},
 {name:"Vintage Damsel",rarity:"Uncommon",chance:"1 in 135",island:"planetary-observatory"},
 {name:"Cosmic Tailfish",rarity:"Uncommon Ext",chance:"1 in 200",island:"planetary-observatory"},
 {name:"Jawel Tang",rarity:"Rare",chance:"1 in 250",island:"planetary-observatory"},
 {name:"Traffic Cone Fish",rarity:"Rare",chance:"1 in 300",island:"planetary-observatory"},
 {name:"Cute Octopus",rarity:"Rare",chance:"1 in 300",island:"planetary-observatory"},
 {name:"Candy Butterfly",rarity:"Rare",chance:"1 in 375",island:"planetary-observatory"},
 {name:"Cosmic Bass",rarity:"Rare Ext",chance:"1 in 400",island:"planetary-observatory"},
 {name:"Cow Clownfish",rarity:"Epic",chance:"1 in 1k",island:"planetary-observatory"},
 {name:"Expensive Chain",rarity:"Epic",chance:"1 in 1.50k",island:"planetary-observatory"},
 {name:"Blue Moonfish",rarity:"Epic",chance:"1 in 2k",island:"planetary-observatory"},
 {name:"Narwhal",rarity:"Epic",chance:"1 in 2k",island:"planetary-observatory"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"planetary-observatory"},
 {name:"Cosmic Jellyfish",rarity:"Epic Ext",chance:"1 in 3k",island:"planetary-observatory"},
 {name:"Moorish Idol",rarity:"Epic",chance:"1 in 3.33k",island:"planetary-observatory"},
 {name:"Diamond Ring",rarity:"Legendary",chance:"1 in 5k",island:"planetary-observatory"},
 {name:"Slurpfish Chromis",rarity:"Legendary",chance:"1 in 8k",island:"planetary-observatory"},
 {name:"Chrome Tuna",rarity:"Legendary",chance:"1 in 9k",island:"planetary-observatory"},
 {name:"Ruby",rarity:"Legendary",chance:"1 in 15k",island:"planetary-observatory"},
 {name:"Mantan Ray",rarity:"Mythic",chance:"1 in 50k",island:"planetary-observatory"},
 {name:"Cosmic Blobfish",rarity:"Mythic Ext",chance:"1 in 80k",island:"planetary-observatory"},
 {name:"Hammerhead Shark",rarity:"Mythic",chance:"1 in 100k",island:"planetary-observatory"},
 {name:"Sharp One",rarity:"Mythic",chance:"1 in 105k",island:"planetary-observatory"},
 {name:"Cosmic Hammerhead Shark",rarity:"Mythic Ext",chance:"1 in 180k",island:"planetary-observatory"},
 {name:"Blob Shark",rarity:"SECRET",chance:"1 in 250k",island:"planetary-observatory",weight:"532.2kg - 590.5kg",big:"638.5kg - 753.3kg"},
 {name:"Ghost Shark",rarity:"SECRET",chance:"1 in 500k",island:"planetary-observatory",weight:"1.09k kg - 1.21k kg",big:"1.52k kg - 1.69k kg"},
 {name:"Skeleton Narwhal",rarity:"SECRET",chance:"1 in 600k",island:"planetary-observatory",weight:"339kg - 509kg",big:"620kg - 700kg"},
 {name:"Cosmic Mutant Shark",rarity:"SECRET",chance:"1 in 2M",island:"planetary-observatory",weight:"500k kg - 520k kg",big:"530k kg - 640k kg"},
 {name:"Worm Fish",rarity:"SECRET",chance:"1 in 3M",island:"treasure-room",weight:"106.95k kg - 112.04k kg",big:"130.63k kg - 145.85k kg"},
 // Ocean
 {name:"Yellowstate Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Vintage Blue Tang",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Masked Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Conspi Angelfish",rarity:"Common",chance:"1 in 2",island:"ocean"},
 {name:"Skunk Tilefish",rarity:"Common",chance:"1 in 7",island:"ocean"},
 {name:"Fade Tang",rarity:"Common",chance:"1 in 15",island:"ocean"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Cypress Ratua",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Curious Garfish",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Purp Blisfish",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Blue-Banded Goby",rarity:"Uncommon",chance:"1 in 50",island:"ocean"},
 {name:"Tricolore Butterfly",rarity:"Uncommon",chance:"1 in 70",island:"ocean"},
 {name:"Vintage Damsel",rarity:"Uncommon",chance:"1 in 135",island:"ocean"},
 {name:"Jawel Tang",rarity:"Rare",chance:"1 in 250",island:"ocean"},
 {name:"Traffic Cone Fish",rarity:"Rare",chance:"1 in 300",island:"ocean"},
 {name:"Cute Octopus",rarity:"Rare",chance:"1 in 300",island:"ocean"},
 {name:"Candy Butterfly",rarity:"Rare",chance:"1 in 375",island:"ocean"},
 {name:"Cow Clownfish",rarity:"Epic",chance:"1 in 1k",island:"ocean"},
 {name:"Expensive Chain",rarity:"Epic",chance:"1 in 1.50k",island:"ocean"},
 {name:"Blue Moonfish",rarity:"Epic",chance:"1 in 2k",island:"ocean"},
 {name:"Narwhal",rarity:"Epic",chance:"1 in 2k",island:"ocean"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"ocean"},
 {name:"Moorish Idol",rarity:"Epic",chance:"1 in 3.33k",island:"ocean"},
 {name:"Diamond Ring",rarity:"Legendary",chance:"1 in 5k",island:"ocean"},
 {name:"Slurpfish Chromis",rarity:"Legendary",chance:"1 in 8k",island:"ocean"},
 {name:"Chrome Tuna",rarity:"Legendary",chance:"1 in 9k",island:"ocean"},
 {name:"Ruby",rarity:"Legendary",chance:"1 in 15k",island:"ocean"},
 {name:"Mantan Ray",rarity:"Mythic",chance:"1 in 50k",island:"ocean"},
 {name:"Hammerhead Shark",rarity:"Mythic",chance:"1 in 100k",island:"ocean"},
 {name:"Sharp One",rarity:"Mythic",chance:"1 in 105k",island:"ocean"},
 {name:"Blob Shark",rarity:"SECRET",chance:"1 in 250k",island:"ocean",weight:"532.2kg - 590.5kg",big:"638.5kg - 753.3kg"},
 {name:"Ghost Shark",rarity:"SECRET",chance:"1 in 500k",island:"ocean",weight:"1.09k kg - 1.21k kg",big:"1.52k kg - 1.69k kg"},
 {name:"Skeleton Narwhal",rarity:"SECRET",chance:"1 in 600k",island:"ocean",weight:"339kg - 509kg",big:"620kg - 700kg"},
 {name:"Worm Fish",rarity:"SECRET",chance:"1 in 3M",island:"ocean",weight:"106.95k kg - 112.04k kg",big:"130.63k kg - 145.85k kg"},
 {name:"Megalodon",rarity:"SECRET",chance:"1 in 4M",island:"ocean",weather:"Megalodon Hunt",weight:"305k kg - 365k kg",big:"395k kg - 450k kg"},
 {name:"Bloodmoon Whale",rarity:"SECRET",chance:"1 in 5M",island:"ocean",weather:"Admin Bloodmoon",weight:"362.78k kg - 464.18k kg",big:"472.11k kg - 525.58k kg"},
 {name:"Frostmoon Whale",rarity:"SECRET",chance:"1 in 5M",island:"ocean",weather:"Admin Frostmoon",weight:"362.78k kg - 464.18k kg",big:"472.11k kg - 525.58k kg"},
 {name:"Glacial Serpent",rarity:"SECRET",chance:"1 in 6M",island:"ocean",weather:"Glacial Serpent Hunt",weight:"890k kg - 940k kg",big:"960k kg - 990k kg"},
 {name:"Thunderzilla",rarity:"FORGOTTEN",chance:"1 in 30M",island:"ocean",weather:"Thunderzilla Hunt",weight:"920K kg - 970K kg",big:"990K kg - 1.10M kg"},
 // Kohana
 {name:"Reef Chromis",rarity:"Common",chance:"1 in 2",island:"kohana"},
 {name:"Jennifer Dottyback",rarity:"Common",chance:"1 in 2",island:"kohana"},
 {name:"Zoster Butter",rarity:"Common",chance:"1 in 8",island:"kohana"},
 {name:"Boa Angelfish",rarity:"Common",chance:"1 in 15",island:"kohana"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"kohana"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"kohana"},
 {name:"Shrimp Goby",rarity:"Uncommon",chance:"1 in 50",island:"kohana"},
 {name:"Blumato Clownfish",rarity:"Uncommon",chance:"1 in 55",island:"kohana"},
 {name:"Boltback Fish",rarity:"Uncommon",chance:"1 in 100",island:"kohana"},
 {name:"Banded Butterfly",rarity:"Uncommon",chance:"1 in 125",island:"kohana"},
 {name:"Fire Goby",rarity:"Rare",chance:"1 in 250",island:"kohana"},
 {name:"Kau Cardinal",rarity:"Rare",chance:"1 in 750",island:"kohana"},
 {name:"Sushi Cardinal",rarity:"Epic",chance:"1 in 1.25k",island:"kohana"},
 {name:"Longnise Butterfly",rarity:"Epic",chance:"1 in 2.90k",island:"kohana"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"kohana"},
 {name:"Bumblebee Grouper",rarity:"Legendary",chance:"1 in 5k",island:"kohana"},
 {name:"Lobster",rarity:"Legendary",chance:"1 in 25k",island:"kohana"},
 {name:"Longgerhead Turtle",rarity:"Mythic",chance:"1 in 55k",island:"kohana"},
 {name:"Prismy Seahorse",rarity:"Mythic",chance:"1 in 80k",island:"kohana"},
 {name:"Starlight Mantan Ray",rarity:"Mythic",chance:"1 in 80k",island:"kohana"},
 {name:"Lochness Monster",rarity:"SECRET",chance:"1 in 3M",island:"kohana",weight:"260k kg - 295k kg",big:"338k kg - 381k kg"},
 {name:"Everbloom",rarity:"FORGOTTEN",chance:"1 in 25M",island:"kohana",weight:"820k kg - 890k kg",big:"900k kg - 1.20M kg"},
  // Kohana Lab
 {name:"Reef Chromis",rarity:"Common",chance:"1 in 2",island:"kohana-lab"},
 {name:"Jennifer Dottyback",rarity:"Common",chance:"1 in 2",island:"kohana-lab"},
 {name:"Zoster Butter",rarity:"Common",chance:"1 in 8",island:"kohana-lab"},
 {name:"Boa Angelfish",rarity:"Common",chance:"1 in 15",island:"kohana-lab"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"kohana-lab"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"kohana-lab"},
 {name:"Shrimp Goby",rarity:"Uncommon",chance:"1 in 50",island:"kohana-lab"},
 {name:"Blumato Clownfish",rarity:"Uncommon",chance:"1 in 55",island:"kohana-lab"},
 {name:"Bluefin Eel",rarity:"Uncommon Ext",chance:"1 in 60",island:"kohana-lab"},
 {name:"Boltback Fish",rarity:"Uncommon",chance:"1 in 100",island:"kohana-lab"},
 {name:"Banded Butterfly",rarity:"Uncommon",chance:"1 in 125",island:"kohana-lab"},
 {name:"Fire Goby",rarity:"Rare",chance:"1 in 250",island:"kohana-lab"},
 {name:"Kau Cardinal",rarity:"Rare",chance:"1 in 750",island:"kohana-lab"},
 {name:"Sushi Cardinal",rarity:"Epic",chance:"1 in 1.25k",island:"kohana-lab"},
 {name:"Longnise Butterfly",rarity:"Epic",chance:"1 in 2.90k",island:"kohana-lab"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"kohana-lab"},
 {name:"Bumblebee Grouper",rarity:"Legendary",chance:"1 in 5k",island:"kohana-lab"},
 {name:"Lobster",rarity:"Legendary",chance:"1 in 25k",island:"kohana-lab"},
 {name:"Longgerhead Turtle",rarity:"Mythic",chance:"1 in 55k",island:"kohana-lab"},
 {name:"Prismy Seahorse",rarity:"Mythic",chance:"1 in 80k",island:"kohana-lab"},
 {name:"Starlight Mantan Ray",rarity:"Mythic",chance:"1 in 80k",island:"kohana-lab"},
 {name:"Lochness Monster",rarity:"SECRET",chance:"1 in 3M",island:"kohana-lab",weight:"260k kg - 295k kg",big:"338k kg - 381k kg"},
 // Kohana Volcano
 {name:"Volcanic Basslet",rarity:"Common",chance:"1 in 4",island:"kohana-volcano"},
 {name:"Lava Sharpshead",rarity:"Common",chance:"1 in 4",island:"kohana-volcano"},
 {name:"Lava Salmon",rarity:"Common",chance:"1 in 10",island:"kohana-volcano"},
 {name:"Arowana",rarity:"Uncommon",chance:"1 in 50",island:"kohana-volcano"},
 {name:"Lava Sharptooth",rarity:"Uncommon",chance:"1 in 50",island:"kohana-volcano"},
 {name:"Lava Tailfish",rarity:"Uncommon",chance:"1 in 50",island:"kohana-volcano"},
 {name:"Magma Goby",rarity:"Uncommon",chance:"1 in 55",island:"kohana-volcano"},
 {name:"Lava Butterfly",rarity:"Uncommon",chance:"1 in 125",island:"kohana-volcano"},
 {name:"Rockform Cardinal",rarity:"Rare",chance:"1 in 250",island:"kohana-volcano"},
 {name:"Volsail Tang",rarity:"Rare",chance:"1 in 300",island:"kohana-volcano"},
 {name:"Magma Smeltfish",rarity:"Rare",chance:"1 in 300",island:"kohana-volcano"},
 {name:"Magma Tuna",rarity:"Rare",chance:"1 in 300",island:"kohana-volcano"},
 {name:"Magmajaw",rarity:"Epic",chance:"1 in 1k",island:"kohana-volcano"},
 {name:"Magma Pufferfish",rarity:"Epic",chance:"1 in 1.50k",island:"kohana-volcano"},
 {name:"Firecoal Damsel",rarity:"Epic",chance:"1 in 2.50k",island:"kohana-volcano"},
 {name:"Magma Piranha",rarity:"Legendary",chance:"1 in 6k",island:"kohana-volcano"},
 {name:"Magma Crab",rarity:"Legendary",chance:"1 in 8.50k",island:"kohana-volcano"},
 {name:"Lavafin Tuna",rarity:"Legendary",chance:"1 in 10k",island:"kohana-volcano"},
 {name:"Blueflame Ray",rarity:"Mythic",chance:"1 in 93k",island:"kohana-volcano"},
 {name:"Magma Shark",rarity:"Mythic",chance:"1 in 80k",island:"kohana-volcano"},
 {name:"Ancient Magma Whale",rarity:"SECRET",chance:"1 in 5M",island:"kohana-volcano",weight:"630k kg - 740k kg",big:"770k kg - 860k kg"}, 
 // Volcanic Cavern
 {name:"Magma Tail Fish",rarity:"Common Ext",chance:"1 in 4",island:"volcanic-cavern"},
 {name:"Volcanic Basslet",rarity:"Common",chance:"1 in 4",island:"volcanic-cavern"},
 {name:"Lava Sharpshead",rarity:"Common",chance:"1 in 4",island:"volcanic-cavern"},
 {name:"Lava Salmon",rarity:"Common",chance:"1 in 10",island:"volcanic-cavern"},
 {name:"Arowana",rarity:"Uncommon",chance:"1 in 50",island:"volcanic-cavern"},
 {name:"Lava Sharptooth",rarity:"Uncommon",chance:"1 in 50",island:"volcanic-cavern"},
 {name:"Lava Tailfish",rarity:"Uncommon",chance:"1 in 50",island:"volcanic-cavern"},
 {name:"Magma Goby",rarity:"Uncommon",chance:"1 in 55",island:"volcanic-cavern"},
 {name:"Lava Butterfly",rarity:"Uncommon",chance:"1 in 125",island:"volcanic-cavern"},
 {name:"Rockform Cardinal",rarity:"Rare",chance:"1 in 250",island:"volcanic-cavern"},
 {name:"Magma Eel",rarity:"Rare Ext",chance:"1 in 300",island:"volcanic-cavern"},
 {name:"Volsail Tang",rarity:"Rare",chance:"1 in 300",island:"volcanic-cavern"},
 {name:"Magma Smeltfish",rarity:"Rare",chance:"1 in 300",island:"volcanic-cavern"},
 {name:"Magma Tuna",rarity:"Rare",chance:"1 in 300",island:"volcanic-cavern"},
 {name:"Magmajaw",rarity:"Epic",chance:"1 in 1k",island:"volcanic-cavern"},
 {name:"Magma Pufferfish",rarity:"Epic",chance:"1 in 1.50k",island:"volcanic-cavern"},
 {name:"Firecoal Damsel",rarity:"Epic",chance:"1 in 2.50k",island:"volcanic-cavern"},
 {name:"Magma Piranha",rarity:"Legendary",chance:"1 in 6k",island:"volcanic-cavern"},
 {name:"Magma Crab",rarity:"Legendary",chance:"1 in 8.50k",island:"volcanic-cavern"},
 {name:"Lavafin Tuna",rarity:"Legendary",chance:"1 in 10k",island:"volcanic-cavern"},
 {name:"Nine Tailed Fish",rarity:"Legendary Ext",chance:"1 in 15k",island:"volcanic-cavern"},
 {name:"Magma Swordfish",rarity:"Mythic Ext",chance:"1 in 50k",island:"volcanic-cavern"},
 {name:"Magma Ptychodus",rarity:"Mythic Ext",chance:"1 in 55k",island:"volcanic-cavern"},
 {name:"Blueflame Ray",rarity:"Mythic",chance:"1 in 93k",island:"volcanic-cavern"},
 {name:"Magma Shark",rarity:"Mythic",chance:"1 in 80k",island:"volcanic-cavern"},
 {name:"Ancient Magma Whale",rarity:"SECRET",chance:"1 in 5M",island:"volcanic-cavern",weight:"630k kg - 740k kg",big:"770k kg - 860k kg"},
 // Lava Basin
 {name:"Cold Blue Vinny",rarity:"Common",chance:"1 in 8",island:"lava-basin"},
 {name:"Gold Bass",rarity:"Common",chance:"1 in 8",island:"lava-basin"},
 {name:"Zapfin Fish",rarity:"Uncommon",chance:"1 in 70",island:"lava-basin"},
 {name:"Pink Crystak Eel",rarity:"Uncommon",chance:"1 in 100",island:"lava-basin"},
 {name:"Crystal Oni Fish",rarity:"Rare",chance:"1 in 300",island:"lava-basin"},
 {name:"Snappy Toth Fish",rarity:"Rare",chance:"1 in 300",island:"lava-basin"},
 {name:"Driftwood",rarity:"Rare Item",chance:"1 in 600",island:"lava-basin"},
 {name:"Rope",rarity:"Rare Item",chance:"1 in 800",island:"lava-basin"},
 {name:"Crystalized Crab",rarity:"Epic",chance:"1 in 1k",island:"lava-basin"},
 {name:"Crystal Octopus",rarity:"Legendary",chance:"1 in 5k",island:"lava-basin"},
 {name:"Neonnite Fish",rarity:"Legendary",chance:"1 in 11.11k",island:"lava-basin"},
 {name:"Pyrafruit Relic",rarity:"Legendary Item",chance:"1 in 20k",island:"lava-basin"},
 {name:"Embercrux",rarity:"Legendary Item",chance:"1 in 35k",island:"lava-basin"},
 {name:"Runebound Crocodile",rarity:"Mythic",chance:"1 in 60k",island:"lava-basin"},
 {name:"Runic Abyssal Shark",rarity:"Mythic",chance:"1 in 120k",island:"lava-basin"},
 {name:"Caustic Maw",rarity:"SECRET",chance:"1 in 4M",island:"lava-basin",weight:"500k kg - 600k kg",big:"620k kg - 680k kg"},
 // Creater Island
 {name:"Patriot Tang",rarity:"Common",chance:"1 in 10",island:"creater-island"},
 {name:"Pilot Fish",rarity:"Uncommon",chance:"1 in 50",island:"creater-island"},
 {name:"Red Snapper",rarity:"Uncommon",chance:"1 in 50",island:"creater-island"},
 {name:"Blackcap Basslet",rarity:"Uncommon",chance:"1 in 50",island:"creater-island"},
 {name:"Silver Tuna",rarity:"Uncommon",chance:"1 in 60",island:"creater-island"},
 {name:"Parrot Fish",rarity:"Rare",chance:"1 in 300",island:"creater-island"},
 {name:"Catfish",rarity:"Rare",chance:"1 in 300",island:"creater-island"},
 {name:"Sheepshead Fish",rarity:"Rare",chance:"1 in 300",island:"creater-island"},
 {name:"Coney Fish",rarity:"Rare",chance:"1 in 300",island:"creater-island"},
 {name:"Axolotl",rarity:"Legendary",chance:"1 in 6.50k",island:"creater-island"},
 {name:"Hermit Crab",rarity:"Mythic",chance:"1 in 60k",island:"creater-island"},
 {name:"Plasma Shark",rarity:"Mythic",chance:"1 in 225k",island:"creater-island"},
 {name:"Plasma Serpent",rarity:"Mythic",chance:"1 in 225k",island:"creater-island"},
 {name:"Frostborn Shark",rarity:"SECRET",chance:"1 in 500k",island:"creater-island",weight:"7.52k kg - 8.44k kg",big:"10.52k kg - 165.87k kg"},
 {name:"Crystal Goliath",rarity:"SECRET",chance:"1 in 3M",island:"creater-island",weight:"510k kg - 550k kg",big:"570k kg - 620k kg"},
 {name:"Crystalline Behemoth",rarity:"FORGOTTEN",chance:"1 in 20M",island:"creater-island",weight:"1M kg - 1.20M kg",big:"1.30M kg - 1.40M kg"},
 // Coral Reefs
 {name:"Corazon Damsel",rarity:"Common",chance:"1 in 2",island:"coral-reefs"},
 {name:"Specked Butterfly",rarity:"Common",chance:"1 in 2",island:"coral-reefs"},
 {name:"Sail Tang",rarity:"Common",chance:"1 in 5",island:"coral-reefs"},
 {name:"Coral",rarity:"Common",chance:"1 in 6",island:"coral-reefs"},
 {name:"Orange Goby",rarity:"Common",chance:"1 in 7",island:"coral-reefs"},
 {name:"Conch Shell",rarity:"Uncommon",chance:"1 in 50",island:"coral-reefs"},
 {name:"Sea Shell",rarity:"Uncommon",chance:"1 in 50",island:"coral-reefs"},
 {name:"Salmon",rarity:"Uncommon",chance:"1 in 50",island:"coral-reefs"},
 {name:"Flat Fish",rarity:"Uncommon",chance:"1 in 50",island:"coral-reefs"},
 {name:"Flying Fish",rarity:"Uncommon",chance:"1 in 50",island:"coral-reefs"},
 {name:"Wahoo",rarity:"Uncommon",chance:"1 in 65",island:"coral-reefs"},
 {name:"Tricolore Butterfly",rarity:"Uncommon",chance:"1 in 70",island:"coral-reefs"},
 {name:"Lion Fish",rarity:"Uncommon",chance:"1 in 100",island:"coral-reefs"},
 {name:"Maze Angelfish",rarity:"Uncommon",chance:"1 in 125",island:"coral-reefs"},
 {name:"White Clownfish",rarity:"Rare",chance:"1 in 250",island:"coral-reefs"},
 {name:"Scissortail Dartfish",rarity:"Rare",chance:"1 in 300",island:"coral-reefs"},
 {name:"Starfish",rarity:"Rare",chance:"1 in 300",island:"coral-reefs"},
 {name:"Antique Cup",rarity:"Rare",chance:"1 in 300",island:"coral-reefs"},
 {name:"Panther Grouper",rarity:"Epic",chance:"1 in 1k",island:"coral-reefs"},
 {name:"Domino Damsel",rarity:"Epic",chance:"1 in 1.50",island:"coral-reefs"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"coral-reefs"},
 {name:"Starjam Tang",rarity:"Legendary",chance:"1 in 5k",island:"coral-reefs"},
 {name:"Pink Dolphin",rarity:"Legendary",chance:"1 in 5k",island:"coral-reefs"},
 {name:"Greenbee Grouper",rarity:"Legendary",chance:"1 in 6k",island:"coral-reefs"},
 {name:"Saw Fish",rarity:"Legendary",chance:"1 in 15k",island:"coral-reefs"},
 {name:"Blue Lobster",rarity:"Legendary",chance:"1 in 25k",island:"coral-reefs"},
 {name:"Hawks Tutle",rarity:"Mythic",chance:"1 in 75k",island:"coral-reefs"},
 {name:"Luminous Fish",rarity:"Mythic",chance:"1 in 80k",island:"coral-reefs"},
 {name:"Eerie Shark",rarity:"SECRET",chance:"1 in 250k",island:"coral-reefs",weight:"1.01k kg - 1.83k kg",big:"2.23k kg - 2.81k kg"},
 {name:"Monster Shark",rarity:"SECRET",chance:"1 in 2.50M",island:"coral-reefs",weight:"130.41k kg - 165.61k kg",big:"185.10k kg - 245.17k kg"},
 // Esoteric Depths
 {name:"Ash Basslet",rarity:"Common",chance:"1 in 2",island:"esoteric-depths"},
 {name:"Rockfish",rarity:"Uncommon",chance:"1 in 50",island:"esoteric-depths"},
 {name:"Coal Tang",rarity:"Uncommon",chance:"1 in 50",island:"esoteric-depths"},
 {name:"Void Eel",rarity:"Uncommon",chance:"1 in 65",island:"esoteric-depths"},
 {name:"Sea Anemone",rarity:"Rare",chance:"1 in 300",island:"esoteric-depths"},
 {name:"Dark Tentacle",rarity:"Rare",chance:"1 in 300",island:"esoteric-depths"},
 {name:"Charmed Tang",rarity:"Rare",chance:"1 in 325",island:"esoteric-depths"},
 {name:"Iron Domefin",rarity:"Epic",chance:"1 in 1k",island:"esoteric-depths"},
 {name:"Starlight Crab",rarity:"Epic",chance:"1 in 1k",island:"esoteric-depths"},
 {name:"Astra Damsel",rarity:"Epic",chance:"1 in 2k",island:"esoteric-depths"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"esoteric-depths"},
 {name:"Enchanted Angelfish",rarity:"Legendary",chance:"1 in 5k",island:"esoteric-depths"},
 {name:"Fish Fossil",rarity:"Legendary",chance:"1 in 5k",island:"esoteric-depths"},
 {name:"Magic Tang",rarity:"Legendary",chance:"1 in 7.50k",island:"esoteric-depths"},
 {name:"Abyss Seahorse",rarity:"Mythic",chance:"1 in 85k",island:"esoteric-depths"},
 {name:"Hybodus Shark",rarity:"Mythic",chance:"1 in 150k",island:"esoteric-depths"},
 {name:"Thin Armor Shark",rarity:"SECRET",chance:"1 in 300k",island:"esoteric-depths",weight:"14.15k kg - 21.23k kg",big:"24.84k kg - 31.46k kg"},
 {name:"Scare",rarity:"SECRET",chance:"1 in 3M",island:"esoteric-depths",weight:"142.33k kg - 165.10k kg",big:"182.75k kg - 212.01k kg"},
 // Tropical Grove
 {name:"Orange Basslet",rarity:"Uncommon",chance:"1 in 50",island:"tropical-grove"},
 {name:"Racoon Butterfly Fish",rarity:"Uncommon",chance:"1 in 50",island:"tropical-grove"},
 {name:"Sand Eel",rarity:"Uncommon",chance:"1 in 60",island:"tropical-grove"},
 {name:"Smarty Mcfish",rarity:"Uncommon",chance:"1 in 70",island:"tropical-grove"},
 {name:"Scissortail Dartfish",rarity:"Rare",chance:"1 in 300",island:"tropical-grove"},
 {name:"Crismon Piranha",rarity:"Rare",chance:"1 in 300",island:"tropical-grove"},
 {name:"King Mackerel",rarity:"Rare",chance:"1 in 300",island:"tropical-grove"},
 {name:"Pufferfish",rarity:"Epic",chance:"1 in 1.50k",island:"tropical-grove"},
 {name:"Enchant Stone",rarity:"Epic Item",chance:"1 in 2.90k",island:"tropical-grove"},
 {name:"Ruby",rarity:"Legendary",chance:"1 in 15k",island:"tropical-grove"},
 {name:"Strippled Seahorse",rarity:"Mythic",chance:"1 in 95k",island:"tropical-grove"},
 {name:"Thresher Shark",rarity:"Mythic",chance:"1 in 95k",island:"tropical-grove"},
 {name:"Fossilized Shark",rarity:"Mythic",chance:"1 in 100k",island:"tropical-grove"},
 {name:"Great Whale",rarity:"SECRET",chance:"1 in 950k",island:"tropical-grove",weight:"90.70k kg - 116.04k kg",big:"118.03k kg - 131.40k kg"},
 {name:"Coral Whale",rarity:"SECRET",chance:"1 in 2M",island:"tropical-grove",weight:"102k kg - 115k kg",big:"120k kg - 138k kg"},
 // Sisyphus Statue
 {name:"Electric Eel",rarity:"Common",chance:"1 in 2",island:"sisyphus-statue"},
 {name:"Boar Fish",rarity:"Common",chance:"1 in 2",island:"sisyphus-statue"},
 {name:"Dark Eel",rarity:"Uncommon",chance:"1 in 50",island:"sisyphus-statue"},
 {name:"Viperfish",rarity:"Uncommon",chance:"1 in 50",island:"sisyphus-statue"},
 {name:"Spotted Lantern Fish",rarity:"Uncommon",chance:"1 in 50",island:"sisyphus-statue"},
 {name:"Jellyfish",rarity:"Rare",chance:"1 in 300",island:"sisyphus-statue"},
 {name:"Liar Nose Fish",rarity:"Rare",chance:"1 in 300",island:"sisyphus-statue"},
 {name:"Pearl",rarity:"Rare",chance:"1 in 300",island:"sisyphus-statue"},
 {name:"Fangtooth",rarity:"Epic",chance:"1 in 2k",island:"sisyphus-statue"},
 {name:"Vampire Squid",rarity:"Epic",chance:"1 in 3k",island:"sisyphus-statue"},
 {name:"Monk Fish",rarity:"Epic",chance:"1 in 3k",island:"sisyphus-statue"},
 {name:"Angler Fish",rarity:"Epic",chance:"1 in 3k",island:"sisyphus-statue"},
 {name:"Synodontis",rarity:"Legendary",chance:"1 in 5k",island:"sisyphus-statue"},
 {name:"Deep Sea Crab",rarity:"Legendary",chance:"1 in 5k",island:"sisyphus-statue"},
 {name:"Armor Catfish",rarity:"Mythic",chance:"1 in 50k",island:"sisyphus-statue"},
 {name:"Blob Fish",rarity:"Mythic",chance:"1 in 50k",island:"sisyphus-statue"},
 {name:"Cryoshade Glider",rarity:"SECRET",chance:"1 in 450k",island:"sisyphus-statue",weight:"10.50k kg - 11.50k kg",big:"14.50k kg - 17.20k kg"},
 {name:"Panther Eel",rarity:"SECRET",chance:"1 in 750k",island:"sisyphus-statue",weight:"90.67k kg - 113.40k kg",big:"123.92k kg - 146.85k kg"},
 {name:"Giant Squid",rarity:"SECRET",chance:"1 in 800k",island:"sisyphus-statue",weight:"103.53k kg - 112.80k kg",big:"120.70k kg - 140.61k kg"},
 {name:"Depthseeker Ray",rarity:"SECRET",chance:"1 in 1.2M",island:"sisyphus-statue",time:"17:78 -> 06:09",weather:"Night",weight:"145k kg - 155k kg",big:"165k kg - 205k kg"},
 {name:"Pelagon",rarity:"SECRET",chance:"1 in 4.50M",island:"sisyphus-statue",weight:"660k kg - 710k kg",big:"750k kg - 810k kg"},
 // Treasure Room
 {name:"Dead Fish",rarity:"Common",chance:"1 in 4",island:"treasure-room"},
 {name:"Skeleton Fish",rarity:"Common",chance:"1 in 10",island:"treasure-room"},
 {name:"Swordfish",rarity:"Uncommon",chance:"1 in 50",island:"treasure-room"},
 {name:"Viperfish",rarity:"Uncommon",chance:"1 in 50",island:"treasure-room"},
 {name:"Spotted Lantern Fish",rarity:"Uncommon",chance:"1 in 50",island:"treasure-room"},
 {name:"Jellyfish",rarity:"Rare",chance:"1 in 300",island:"treasure-room"},
 {name:"Antique Watch",rarity:"Epic",chance:"1 in 1.50k",island:"treasure-room"},
 {name:"Fangtooth",rarity:"Epic",chance:"1 in 2k",island:"treasure-room"},
 {name:"Vampire Squid",rarity:"Epic",chance:"1 in 3k",island:"treasure-room"},
 {name:"Monk Fish",rarity:"Epic",chance:"1 in 3k",island:"treasure-room"},
 {name:"Angler Fish",rarity:"Epic",chance:"1 in 3k",island:"treasure-room"},
 {name:"Synodontis",rarity:"Legendary",chance:"1 in 5k",island:"treasure-room"},
 {name:"Deep Sea Crab",rarity:"Legendary",chance:"1 in 5k",island:"treasure-room"},
 {name:"Ruby",rarity:"Legendary",chance:"1 in 15k",island:"treasure-room"},
 {name:"Armor Catfish",rarity:"Mythic",chance:"1 in 50k",island:"treasure-room"},
 {name:"Blob Fish",rarity:"Mythic",chance:"1 in 50k",island:"treasure-room"},
 {name:"Queen Crab",rarity:"SECRET",chance:"1 in 800k",island:"treasure-room",weight:"130.52k kg - 160.96k kg",big:"180.96k kg - 192.31k kg"},
 {name:"King Crab",rarity:"SECRET",chance:"1 in 1.20M",island:"treasure-room",weight:"130.52k kg - 160.96k kg",big:"180.96k kg - 192.31k kg"},
 {name:"Pelagon",rarity:"SECRET",chance:"1 in 4.50M",island:"treasure-room",weight:"660k kg - 710k kg",big:"750k kg - 810k kg"},
 // Ancient Jungle
 {name:"Beanie Leedsicheye",rarity:"Common",chance:"1 in 2",island:"ancient-jungle"},
 {name:"Runic Wispeye",rarity:"Common",chance:"1 in 2",island:"ancient-jungle"},
 {name:"Waveback Fish",rarity:"Common",chance:"1 in 2",island:"ancient-jungle"},
 {name:"Green Gillfish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Ancinet Arapaima",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Abyshorn Fish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Drippy Tucanare",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Sail Fish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Water Snake",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Thinkler Fish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-jungle"},
 {name:"Sophisticated Angler",rarity:"Uncommon",chance:"1 in 70",island:"ancient-jungle"},
 {name:"Red Goatfish",rarity:"Uncommon",chance:"1 in 100",island:"ancient-jungle"},
 {name:"Zebra Snakehead",rarity:"Uncommon",chance:"1 in 150",island:"ancient-jungle"},
 {name:"Parrot Blobfish",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Mossy Fishlet",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Parrot Fish",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Viperangler Fish",rarity:"Rare",chance:"1 in 300",island:"ancient-jungle"},
 {name:"Flowery Fish",rarity:"Rare",chance:"1 in 350",island:"ancient-jungle"},
 {name:"Radiant Catfish",rarity:"Rare",chance:"1 in 400",island:"ancient-jungle"},
 {name:"Spear Guardian",rarity:"Epic",chance:"1 in 1k",island:"ancient-jungle"},
 {name:"Goliath Tiger",rarity:"Epic",chance:"1 in 1k",island:"ancient-jungle"},
 {name:"Seaweed Pufferfish",rarity:"Epic",chance:"1 in 1.50k",island:"ancient-jungle"},
 {name:"Crescent Artifact",rarity:"Epic Item",chance:"1 in 2k",island:"ancient-jungle"},
 {name:"Arrow Artifact",rarity:"Epic Item",chance:"1 in 2k",island:"ancient-jungle"},
 {name:"Hourglass Diamond Artifact",rarity:"Epic Item",chance:"1 in 2k",island:"ancient-jungle"},
 {name:"Diamond Artifact",rarity:"Epic Item,",chance:"1 in 2k",island:"ancient-jungle"},
 {name:"Skeleton Angler Fish",rarity:"Epic",chance:"1 in 3k",island:"ancient-jungle"},
 {name:"Temple Spokes Tuna",rarity:"Legendary",chance:"1 in 5k",island:"ancient-jungle"},
 {name:"Manoai Statue Fish",rarity:"Legendary",chance:"1 in 5k",island:"ancient-jungle"},
 {name:"Alligator Snapper",rarity:"Legendary",chance:"1 in 6k",island:"ancient-jungle"},
 {name:"Sacred Guardian Squid",rarity:"Legendary",chance:"1 in 45k",island:"ancient-jungle"},
 {name:"Crocodile",rarity:"Mythic",chance:"1 in 50k",island:"ancient-jungle"},
 {name:"Mosasaur Shark",rarity:"SECRET",chance:"1 in 800k",island:"ancient-jungle",weight:"80.75k kg - 95.88k kg",big:"106.69k kg - 132.26k kg"},
 {name:"King Jelly",rarity:"SECRET",chance:"1 in 1.50M",island:"ancient-jungle",weight:"160k kg - 190k kg",big:"180k kg - 200k kg"},
 {name:"Ragnarex",rarity:"FORGOTTEN",chance:"1 in 35M",island:"ancient-jungle",weight:"1M kg - 1.10M kg",big:"1.15M kg - 1.30M kg"},
 // Underground Cellar
 {name:"Beanie Leedsicheye",rarity:"Common",chance:"1 in 2",island:"underground-cellar"},
 {name:"Runic Wispeye",rarity:"Common",chance:"1 in 2",island:"underground-cellar"},
 {name:"Waveback Fish",rarity:"Common",chance:"1 in 2",island:"underground-cellar"},
 {name:"Ancinet Arapaima",rarity:"Uncommon",chance:"1 in 50",island:"underground-cellar"},
 {name:"Abyshorn Fish",rarity:"Uncommon",chance:"1 in 50",island:"underground-cellar"},
 {name:"Drippy Tucanare",rarity:"Uncommon",chance:"1 in 50",island:"underground-cellar"},
 {name:"Sail Fish",rarity:"Uncommon",chance:"1 in 50",island:"underground-cellar"},
 {name:"Water Snake",rarity:"Uncommon",chance:"1 in 50",island:"underground-cellar"},
 {name:"Red Goatfish",rarity:"Uncommon",chance:"1 in 100",island:"underground-cellar"},
 {name:"Zebra Snakehead",rarity:"Uncommon",chance:"1 in 150",island:"underground-cellar"},
 {name:"Lunar Crescent Fish",rarity:"Rare Ext",chance:"1 in 300",island:"underground-cellar"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"underground-cellar"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"underground-cellar"},
 {name:"Mossy Fishlet",rarity:"Rare",chance:"1 in 300",island:"underground-cellar"},
 {name:"Parrot Fish",rarity:"Rare",chance:"1 in 300",island:"underground-cellar"},
 {name:"Viperangler Fish",rarity:"Rare",chance:"1 in 300",island:"underground-cellar"},
 {name:"Spear Guardian",rarity:"Epic",chance:"1 in 1k",island:"underground-cellar"},
 {name:"Goliath Tiger",rarity:"Epic",chance:"1 in 1k",island:"underground-cellar"},
 {name:"Skeleton Angler Fish",rarity:"Epic",chance:"1 in 3k",island:"underground-cellar"},
 {name:"Temple Spokes Tuna",rarity:"Legendary",chance:"1 in 5k",island:"underground-cellar"},
 {name:"Manoai Statue Fish",rarity:"Legendary",chance:"1 in 5k",island:"underground-cellar"},
 {name:"Crystal Salamander",rarity:"Legendary Ext",chance:"1 in 6k",island:"underground-cellar"},
 {name:"Sacred Guardian Squid",rarity:"Legendary",chance:"1 in 45k",island:"underground-cellar"},
 {name:"Crocodile",rarity:"Mythic",chance:"1 in 50k",island:"underground-cellar"},
 {name:"Ancient Whale",rarity:"SECRET",chance:"1 in 2.75M",island:"underground-cellar",weight:"310.89k kg - 355.73k kg",big:"388.50k kg - 410.94k kg"},
 // Sacred Temple
 {name:"Beanie Leedsicheye",rarity:"Common",chance:"1 in 2",island:"sacred-temple"},
 {name:"Runic Wispeye",rarity:"Common",chance:"1 in 2",island:"sacred-temple"},
 {name:"Waveback Fish",rarity:"Common",chance:"1 in 2",island:"sacred-temple"},
 {name:"Green Gillfish",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Ancinet Arapaima",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Abyshorn Fish",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Drippy Tucanare",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Sail Fish",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Water Snake",rarity:"Uncommon",chance:"1 in 50",island:"sacred-temple"},
 {name:"Red Goatfish",rarity:"Uncommon",chance:"1 in 100",island:"sacred-temple"},
 {name:"Zebra Snakehead",rarity:"Uncommon",chance:"1 in 150",island:"sacred-temple"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"sacred-temple"},
 {name:"Freshwater Piranha",rarity:"Rare",chance:"1 in 300",island:"sacred-temple"},
 {name:"Mossy Fishlet",rarity:"Rare",chance:"1 in 300",island:"sacred-temple"},
 {name:"Parrot Fish",rarity:"Rare",chance:"1 in 300",island:"sacred-temple"},
 {name:"Viperangler Fish",rarity:"Rare",chance:"1 in 300",island:"sacred-temple"},
 {name:"Sparkly Eel",rarity:"Rare",chance:"1 in 400",island:"sacred-temple"},
 {name:"Spear Guardian",rarity:"Epic",chance:"1 in 1k",island:"sacred-temple"},
 {name:"Goliath Tiger",rarity:"Epic",chance:"1 in 1k",island:"sacred-temple"},
 {name:"Skeleton Angler Fish",rarity:"Epic",chance:"1 in 3k",island:"sacred-temple"},
 {name:"Temple Spokes Tuna",rarity:"Legendary",chance:"1 in 5k",island:"sacred-temple"},
 {name:"Manoai Statue Fish",rarity:"Legendary",chance:"1 in 5k",island:"sacred-temple"},
 {name:"Sacred Guardian Squid",rarity:"Legendary",chance:"1 in 45k",island:"sacred-temple"},
 {name:"Crocodile",rarity:"Mythic",chance:"1 in 50k",island:"sacred-temple"},
 {name:"Viridis Luker",rarity:"SECRET",chance:"1 in 1.40M",island:"sacred-temple",weight:"170k kg - 190k kg",big:"200k kg - 245k kg"},
 {name:"Bone Whale",rarity:"SECRET",chance:"1 in 2M",island:"sacred-temple",weight:"230.88k kg - 275.68k kg",big:"288.23k kg - 310.37k kg"},
 {name:"Elshark Gran Maja",rarity:"SECRET",chance:"1 in 4M",island:"sacred-temple",weight:"450k kg - 520k kg",big:"560k kg - 650k kg"},
 // Ancient Ruin
 {name:"Night Glider Fish",rarity:"Common",chance:"1 in 2",island:"ancient-ruin"},
 {name:"Sona Fin Fish",rarity:"Common",chance:"1 in 2",island:"ancient-ruin"},
 {name:"Wing Parrotfish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-ruin"},
 {name:"Foxtrot Koanfish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-ruin"},
 {name:"Doober Fish",rarity:"Uncommon",chance:"1 in 50",island:"ancient-ruin"},
 {name:"Baby Shrimp",rarity:"Uncommon",chance:"1 in 50",island:"ancient-ruin"},
 {name:"Boney Eel",rarity:"Rare",chance:"1 in 300",island:"ancient-ruin"},
 {name:"Pirate Blue Lobster",rarity:"Rare",chance:"1 in 300",island:"ancient-ruin"},
 {name:"Toothy Fish",rarity:"Rare",chance:"1 in 300",island:"ancient-ruin"},
 {name:"Blobby Shieldfish",rarity:"Epic",chance:"1 in 1k",island:"ancient-ruin"},
 {name:"Angrylion Fish",rarity:"Epic",chance:"1 in 2k",island:"ancient-ruin"},
 {name:"Primal Lobster",rarity:"Legendary",chance:"1 in 5k",island:"ancient-ruin"},
 {name:"Primal Lobster",rarity:"Legendary",chance:"1 in 5k",island:"ancient-ruin"},
 {name:"Ancient Pufferfish",rarity:"Legendary",chance:"1 in 5k",island:"ancient-ruin"},
 {name:"Primal Axolotl",rarity:"Legendary",chance:"1 in 10k",island:"ancient-ruin"},
 {name:"Runic Axolotl",rarity:"Legendary",chance:"1 in 10k",island:"ancient-ruin"},
 {name:"Flying Manta",rarity:"Legendary",chance:"1 in 15k",island:"ancient-ruin"},
 {name:"Evolved Enchant Stone",rarity:"Legendary Item",chance:"1 in 30k",island:"ancient-ruin"},
 {name:"Sea Crustacean",rarity:"Mythic",chance:"1 in 50k",island:"ancient-ruin"},
 {name:"Sea Crustacean",rarity:"Mythic",chance:"1 in 50k",island:"ancient-ruin"},
 {name:"Ancinet Squid",rarity:"Mythic",chance:"1 in 90k",island:"ancient-ruin"},
 {name:"Runic Squid",rarity:"Mythic",chance:"1 in 90k",island:"ancient-ruin"},
 {name:"Cavern Dweller",rarity:"Mythic",chance:"1 in 100k",island:"ancient-ruin"},
 {name:"Primordial Octopus",rarity:"Mythic",chance:"1 in 150k",island:"ancient-ruin"},
 {name:"Flatheaded Whale Shark",rarity:"Mythic",chance:"1 in 200k",island:"ancient-ruin"},
 {name:"Gladiator Shark",rarity:"SECRET",chance:"1 in 1M",island:"ancient-ruin",weight:"10.29k kg - 16.43k kg",big:"19.43k kg - 25k kg"},
 {name:"Ancient Lochness Monster",rarity:"SECRET",chance:"1 in 3M",island:"ancient-ruin",weather:"Ancient Ruin",weight:"260k kg - 295k kg",big:"338k kg - 381k kg"},
 {name:"Elshark Gran Maja",rarity:"SECRET",chance:"1 in 4M",island:"ancient-ruin",weight:"450k kg - 520k kg",big:"560k kg - 650k kg"},

 // ???
 {name:"Sunken Hadalith",rarity:"SECRET",chance:"???",island:"unknown",time:"???",weather:"???",weight:"???",big:"???"},
 {name:"Robot Kraken",rarity:"SECRET",chance:"1 in 3.50M",island:"unknown",weight:"259.82k kg - 389.73k kg",big:"419.60k kg - 586.47k kg"},
];
const STONES = [
 {id:"enchant-stone",name:"Enchant Stone",
  desc:"Apply a raondom buff to your Fishing Rod!",
  obtain:["You can get those Enchant Stones ( 1 in 2.9k ) at Fisherman Island, Ocean, Kohana, Coral Reefs, Esoteric Depths, Tropical Grove, Planetary Observatory and Kohana Lab."],
  where:"Esoteric Depths Altar."},
 {id:"super-enchant-stone",name:"Super Enchant Stone",
  desc:"Supercharge your Fishing Rod!",
  obtain:["You can obtain it by completing a quest from the Esoteric Gatekeeper NPC in the Esoteric Depths.",
    "Quest : Enchant a rod 5 times" ],
  where:"Esoteric Depths Altar."},
 {id:"transcended-stone",name:"Transcended Stone",
  desc:"Allows you to apply a second rod enchant.",
  obtain:["Sacrifice a SECRET fish for 1 Transcended Stone at the Temple Guardian NPC in the Sacred Temple."],
  where:"Sacred Temple Altar."},
 {id:"evolved-enchant-stone",name:"Evolved Enchant Stone",
  desc:"Apply a evolved buff to your Fishing Rod!",
  obtain:["You can get those Evolved Enchant Stone ( 1 in 30k ) at Ancient Ruin."],
  where:"Esoteric Depths Altar."},
 {id:"runic-enchant-stone",name:"Runic Enchant Stone",
  desc:"Apply a runic buff to your Fishing Rod!",
  obtain:["You can get those Runic Enchant Stone ( 1 in 700k ) at Underwater city and Sewers."],
  where:"Esoteric Depths Altar."},
 {id:"withering-stone",name:"Withering Stone",
  desc:"Apply the Withering Stone buff which can only be used on your second Withering Rod to enchant it!",
  obtain:["You can obtain it by completing a quest from the Lucid NPC in the Copper canyon.",
    "Quest : Own a Withering Rod", "Catch a Runic Enchant Stone", "Catch 4M rarity worh of fish",
    "Catch 50 fish while using PERFECT! throw" ],
  where:"Sacred Temple Altar."}
];
const ENCHANTS = [
  // Enchant Stone
 {name:"Stargazer I",effect:"+60% Luck at night",stone:"enchant-stone",chance:"7.5%"},
 {name:"Glistening I",effect:"+10% Shiny fish chance",stone:"enchant-stone",chance:"7.5%"},
 {name:"Stormhunter I",effect:"+80% Luck during rain",stone:"enchant-stone",chance:"7.5%"},
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"enchant-stone",chance:"5%"},
 {name:"XPerienced I",effect:"x1.5 XP from all fish catches",stone:"enchant-stone",chance:"7.5%"},
 {name:"Mutation Hunter I",effect:"+10% Chance for mutation",stone:"enchant-stone",chance:"10%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"enchant-stone",chance:"5%"},
 {name:"Big Hunter I",effect:"Makes fish 10% bigger",stone:"enchant-stone",chance:"7.5%"},
 {name:"Reeler I",effect:"Reel in fish 7% faster",stone:"enchant-stone",chance:"7.5%"},
 {name:"Gold Digger I",effect:"Constant 10% chance for Gold mutation",stone:"enchant-stone",chance:"7.5%"},
 {name:"Leprechaun I",effect:"+30% Luck",stone:"enchant-stone",chance:"10%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"enchant-stone",chance:"7.5%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"enchant-stone",chance:"5%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"enchant-stone",chance:"5%"},
 // Super Enchant Stone
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"super-enchant-stone",chance:"20%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"super-enchant-stone",chance:"20%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"super-enchant-stone",chance:"20%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"super-enchant-stone",chance:"20%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"super-enchant-stone",chance:"20%"},
 // Transcended Stone
 {name:"Perfection",effect:"Gurenteed 'Perfect' throws while auto fishing",stone:"transcended-stone",chance:"4%"},
 {name:"Prismatic I",effect:"Rainbow boost activates with 8 less throws",stone:"transcended-stone",chance:"5%"},
 {name:"Stargazer I",effect:"+60% Luck at night",stone:"transcended-stone",chance:"7.5%"},
 {name:"Glistening I",effect:"+10% Shiny fish chance",stone:"transcended-stone",chance:"7.5%"},
 {name:"Stormhunter I",effect:"+80% Luck during rain",stone:"transcended-stone",chance:"7.5%"},
 {name:"XPerienced I",effect:"x1.5 XP from all fish catches",stone:"transcended-stone",chance:"7.5%"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"transcended-stone",chance:"5%"},
 {name:"Big Hunter I",effect:"Makes fish 10% bigger",stone:"transcended-stone",chance:"7.5%"},
 {name:"Reeler I",effect:"Reel in fish 7% faster",stone:"transcended-stone",chance:"7.5%"},
 {name:"Gold Digger I",effect:"Constant 10% chance for Gold mutation",stone:"transcended-stone",chance:"7.5%"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"transcended-stone",chance:"7.5%"},
 {name:"Mutation Hunter II",effect:"+30% Chance for mutation",stone:"transcended-stone",chance:"5%"},
 {name:"Leprechaun II",effect:"+50% Luck",stone:"transcended-stone",chance:"5%"},
 // Evolved Enchant Stone
 {name:"SECRET Hunter",effect:"+400% SECRET Chance",stone:"evolved-enchant-stone"},
 {name:"Gemstone Hunter I",effect:"+35% Gemstone mutation chance",stone:"evolved-enchant-stone"},
 {name:"Cursed I",effect:"-75% Luck, +75% mutation chance",stone:"evolved-enchant-stone"},
 {name:"Stargazer II",effect:"+100% Luck at night",stone:"evolved-enchant-stone"},
 {name:"Empowered I",effect:"+20% luck, +10% faster reel",stone:"evolved-enchant-stone"},
 {name:"Shark Hunter I",effect:"Increase all Shark chances by 175%",stone:"evolved-enchant-stone"},
 {name:"Stormhunter II",effect:"+140% Luck during rain",stone:"evolved-enchant-stone"},
 {name:"Fairy Hunter I",effect:"+35 Fairy Dust mutation chance",stone:"evolved-enchant-stone"},
 {name:"Reeler II",effect:"Reel in fish 15% faster",stone:"evolved-enchant-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"evolved-enchant-stone"},
 // Runic Enchant Stone
 {name:"FORGOTTEN Hunter",effect:"+500% FORGOTTEN Chance",stone:"runic-enchant-stone"},
 {name:"Glistening II",effect:"+20% Shiny fish chance",stone:"runic-enchant-stone"},
 {name:"XPerienced II",effect:"x2 XP from all fish catches",stone:"runic-enchant-stone"},
 {name:"Shark Hunter II",effect:"Increase all Shark chances by 275%",stone:"runic-enchant-stone"},
 {name:"Cursed II",effect:"-100% Luck, +100% mutation chance",stone:"runic-enchant-stone"},
 {name:"Empowered II",effect:"+35% luck, +15% faster reel",stone:"runic-enchant-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"runic-enchant-stone"},
 // Withering Stone
 {name:"SECRET Hunter",effect:"+400% SECRET Chance",stone:"withering-stone"},
 {name:"Shark Hunter II",effect:"Increase all Shark chances by 275%",stone:"withering-stone"},
 {name:"Fairy Hunter II",effect:"+60 Fairy Dust mutation chance",stone:"withering-stone"},
 {name:"Big Hunter II",effect:"Makes fish 15% bigger",stone:"withering-stone"},
 {name:"Cursed II",effect:"-100% Luck, +100% mutation chance",stone:"withering-stone"},
 {name:"Mutation Hunter III",effect:"+45% Chance for mutation",stone:"withering-stone"},
 {name:"Empowered III",effect:"+65% luck, +15% faster reel",stone:"withering-stone"}
];
const SOON = [
 {id:"rods",name:"Rods",desc:"Semua pancingan, statistik, dan cara mendapatkannya."},
 {id:"baits",name:"Baits",desc:"Umpan dan efek Luck-nya."}
];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const PH="data:image/svg+xml,"+encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120'><rect width='120' height='120' rx='14' fill='#c9dadf'/><text x='60' y='66' font-size='13' text-anchor='middle' fill='#5b7580' font-family='sans-serif'>Proses...</text></svg>");
const img=(src,alt,cls)=>`<img class="${cls||""}" src="${src}" alt="${alt}" loading="lazy" onerror="this.onerror=null;this.src=PH">`;
